[package]
name = "photo-cropper"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
clap = { version = "4.5", features = ["derive"] }
opencv = { version = "0.92", features = [
    "clang-runtime",
    "calib3d",
    "imgcodecs",
    "imgproc",
    "photo",
] }
walkdir = "2"
